// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/shared/Navbar";
// import WorksProvider from "@/context/WorksContext";
// import { ToastContainer } from "react-toastify";

//updated

// import "react-toastify/dist/ReactToastify.css";
// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";
// import Navbar from "@/components/shared/Navbar";
// import WorksProvider from "@/context/WorksContext";
// import { ToastContainer } from "react-toastify";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }: LayoutProps<"/">) {
//   return (
//     <html
//       lang="en"
//       data-theme="dark"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">
//         <WorksProvider>
//           <Navbar />
//           {children}
//           <h2 className="font-bold text-5xl bg-yellow-400">Footer</h2>
//           <ToastContainer />
//         </WorksProvider>
//       </body>
//     </html>
//   );
// }

// import "react-toastify/dist/ReactToastify.css";

// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import { ToastContainer } from "react-toastify";

// import "./globals.css";
// import Navbar from "@/components/shared/Navbar";
// import WorksProvider from "@/context/WorksContext";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       data-theme="dark"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="flex min-h-full flex-col">
//         <WorksProvider>
//           <Navbar />
//           {children}
//           <h2 className="bg-yellow-400 text-5xl font-bold">Footer</h2>

//           <ToastContainer position="top-right" autoClose={2500} />
//         </WorksProvider>
//       </body>
//     </html>
//   );
// }

import "react-toastify/dist/ReactToastify.css";

import type { Metadata } from "next";
import type { ReactNode } from "react";
import { Geist, Geist_Mono } from "next/font/google";
import { ToastContainer } from "react-toastify";

import "./globals.css";
import Navbar from "@/components/shared/Navbar";
import WorksProvider from "@/context/WorksContext";
import Footer from "@/components/shared/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: ReactNode }>) {
  return (
    <html
      lang="en"
      data-theme="dark"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col">
        <WorksProvider>
          <Navbar />
          {children}
          <Footer />
          <ToastContainer position="top-right" autoClose={2500} />
        </WorksProvider>
      </body>
    </html>
  );
}
